# Generated by Django 5.1.6 on 2025-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0005_address3_student3'),
    ]

    operations = [
        migrations.AddField(
            model_name='student3',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
