# Generated by Django 5.1.6 on 2025-04-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0006_student3_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student3',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='student/'),
        ),
    ]
